### ISSUE TITLE
We get Cannot read property 'parse' of undefined

### ISSUE THREAD

**Issue by TAKEDA-Takashi** [taichi/vscode-textlint#11]
I got a "Cannot read property" error in the following environment.

- OS: macOS 10.14.6
- VSCode: 1.38.1
- textlint: 11.3.1
- vscode-textlint: 0.7.0

Detailed error message.

```
[Error - 9:50:21 AM] Cannot read property 'parse' of undefined
TypeError: Cannot read property 'parse' of undefined
    at repo.newEngine.then.engine (/path/to/.vscode/extensions/taichi.vscode-textlint-0.7.0/node_modules/@taichi/vscode-textlint-server/lib/server.js:166:61)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

I think that the way of writing import is wrong.

https://github.com/taichi/vscode-textlint/blob/master/textlint-server/src/server.ts#L9

**Comment by taichi** [comment]
thanks for your report. I released fixed version.
please try it.
