### ISSUE TITLE
Add TeX to filetypes

### ISSUE THREAD

**Issue by ta2gch** [taichi/vscode-textlint#7]
Thank you for the great extension. I enjoy writing document with this extension.
I make the new plugin for textlint, that supports TeX file. https://github.com/ta2gch/textlint-plugin-latex2e
I hope to use my plugin with this extension.

Please add TeX to filetypes of your extension.

**Comment by taichi** [comment]
it's cool!
Do you use [Visual Studio Code LaTeX Workshop Extension](https://github.com/James-Yu/LaTeX-Workshop) ?

**Comment by ta2gch** [comment]
Yes, I hope to enable textlint at LaTeX Workshop.
I think LaTeX Workshop is the most powerfull next generation of LaTeX writing environment.
But there is no grammarcheck like MS Work and other document system. This issue makes it the most most powerfull writing environment in the all document system.

**Comment by taichi** [comment]
ok, i try to support Tex types.

**Comment by taichi** [comment]
bump 0.6.5.

this version supports tex types including `.tex`, `.latex`, `.doctex`.
but work with LaTeX Workshop.

**Comment by ta2gch** [comment]
Cool!
