### ISSUE TITLE
Recognize additional extensions

### ISSUE THREAD

**Issue by karak** [taichi/vscode-textlint#8]
I uses "textlint-plugin-html" for *.vue files.

But vscode doesn't report errors for them while command line works fine.

You could reproduce this issue out of <https://github.com/karak/vscode-textlint-issue-vue>.

**Comment by taichi** [comment]
i'm sorry about late response.

this issue is not happen to my environment.

![image](https://user-images.githubusercontent.com/66100/54268968-b9d00a80-45bf-11e9-91d6-3f6f064960f7.png)

please newer version.
